name: "cityscape"
version: "1.0.0"
config-version: 2

profile: "cityscape"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  raw_schema: "raw"

models:
  cityscape:
    +materialized: view
    staging:
      +tags: ["stg"]
      mlb:
        +schema: mlb_staging
      nba:
        +schema: nba_staging
      nfl:
        +schema: nfl_staging
      nhl:
        +schema: nhl_staging
    intermediate:
      +tags: ["int"]
      mlb:
        +schema: mlb_intermediate
      nba:
        +schema: nba_intermediate
      nfl:
        +schema: nfl_intermediate
      nhl:
        +schema: nhl_intermediate
    marts:
      +materialized: table
      +tags: ["marts"]
      mlb:
        +schema: mlb_marts
    core:
      +materialized: table
      +tags: ["core", "deprecated"]
      mlb:
        +schema: mlb_core
      nba:
        +schema: nba_core
      nfl:
        +schema: nfl_core
      nhl:
        +schema: nhl_core
    modeling:
      +materialized: table
      +tags: ["modeling"]
      mlb:
        +schema: mlb_modeling
